### ISSUE TITLE
`yarn relay` fails with missing src, schema

### ISSUE THREAD

**Issue by trepidacious** [ricglz0201/pokemon-relay-app#4]
When I run `yarn relay`, I get the following error:

```
Missing required arguments: schema, src
error Command failed with exit code 1.
```

I believe these are set up in `relay.config.js` so should be used, however I noticed the [Relay installation instructions](https://relay.dev/docs/getting-started/installation-and-setup/#set-up-relay-with-a-single-config-file) now include `yarn add --dev relay-config`. If I add this to your project `yarn relay` works as normal.

By the way thanks for the example app - really useful to see everything working in a simple example.

**Comment by ricglz** [comment]
Hey, glad that the app has been useful. Just updated the repo with the changes, will close the issue hoping everything works after this
